---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=true cache_valid_time=600

    - name: Install Avahi Daemon
      apt: name=avahi-daemon

    - name: Install Samba
      apt: name=samba

    - name: webmin | Add webmin repo 
      apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: webmin | Add webmin mirror repo 
      apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: webmin | Addkey webmin
      apt_key: url=http://www.webmin.com/jcameron-key.asc  state=present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: webmin | Install webmin
      apt: pkg={{ item }} state=present update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      with_items:
       - webmin

    - name: Install asterisk
      apt: name=asterisk

    - name: install linux linux-headers
      action: shell apt-get install -y linux-headers-$(uname -r)

    - name: Install FreePBX depends
      apt: pkg={{item}} state=installed
      with_items:
       - build-essential
       - openssh-server
       - apache2
       - mysql-server
       - mysql-client
       - bison
       - flex
       - php5 
       - php5-curl
       - php5-cli
       - php5-mysql
       - php-pear
       - php-db
       - php5-gd
       - curl
       - sox
       - libncurses5-dev
       - libssl-dev
       - libmysqlclient-dev
       - mpg123
       - libxml2-dev
       - libnewt-dev
       - sqlite3
       - libsqlite3-dev
       - pkg-config
       - automake
       - libtool
       - autoconf
       - git
       - subversion
       - unixodbc-dev
       - uuid
       - uuid-dev
       - libasound2-dev
       - libogg-dev
       - libvorbis-dev
       - libcurl4-openssl-dev
       - libical-dev
       - libneon27-dev
       - libsrtp0-dev
       - libspandsp-dev
